### ISSUE TITLE
Fix logsignatures to divide by window length

### ISSUE THREAD

**Issue by patrick-kidger** [patrick-kidger/torchcde#12]
At the moment the logsignature functionality is a little buggy, in that it doesn't normalise the logsignature by the length of the interval it's taken over.

This should be fixed in a backward-compatible manner.

**Comment by jambo6** [comment]
Provided the integral is integrated between [0, 1] (which it always should be), then where does this become an issue? The log-signature never needs to be normalised by the interval length.

**Comment by patrick-kidger** [comment]
The integral isn't always integrated over [0, 1]. (Why should it always be?)

I think all that's necessary is removing the multiplication on this line:
https://github.com/patrick-kidger/torchcde/blob/1cc566ccd27e565977a86de3836f43791fb4c204/torchcde/log_ode.py#L81

**Comment by jambo6** [comment]
The log-ODE method is defined as: 
```
Z_b = Z_a + int_0^1 f(Z)logsig_[a, b](X) ds
```
There is never any need to evaluate an integral with limits that are not [0, 1]. 

Perhaps I am misunderstanding, but if it is done in this way then you do not need to worry about dividing by b-a.

**Comment by patrick-kidger** [comment]
What you've written is correct if a=0, b=1.
We can certainly reparameterise for that to be true each time... by dividing by b - a.

**Comment by jambo6** [comment]
Check definition A.8. in https://arxiv.org/pdf/2009.08295.pdf

The integral is over [0, 1] for any interval [a, b]. We divide by (b-a) if we integrate from a to b.

**Comment by patrick-kidger** [comment]
Okay, flipping this around: integrating over [0, 1] (or rather [n, n+1] later on) is indeed what torchcde will be doing by default later on.

Over that region it should be just the logsignature, as you say. Therefore the multiplication I highlighted above should be removed?

To emphasise this: the tests for this check that the derivative on each piece is equal to the logsignature -- whilst using the optional `t` argument. (They predate the `t` argument being optional.) So the tests are verifying that over an interval determined by t (i.e. _not_ of unit length), the vector field is the logsignature (i.e. without a b-a normalisation). Which is a mismatch.

Do you agree?

**Comment by patrick-kidger** [comment]
Closed in version 0.2.0 with the introduction of `logsig_windows`.
