### ISSUE TITLE
generation example

### ISSUE THREAD

**Issue by xiaoiker** [patrick-kidger/torchcde#23]
Hi,
This work is really amazing. But it seems the experiments in your paper are all about classification tasks. Could you please also provide a sequence generation example？Many thanks~

**Comment by patrick-kidger** [comment]
Neural CDEs are appropriate for tasks like classification and regression.

For generative problems, Neural SDEs are probably a better fit. For example see the paper [Neural SDEs as Infinite-Dimensional GANs](https://arxiv.org/abs/2102.03657), and a worked code example in [torchsde](https://github.com/google-research/torchsde/blob/master/examples/sde_gan.py).

**Comment by xiaoiker** [comment]
Thanks for your valubale advise
