### ISSUE TITLE
setup.py and torchsde

### ISSUE THREAD

**Issue by oizin** [patrick-kidger/torchcde#26]
I might be missing something but it looks to me like https://github.com/google-research/torchsde is up to version 0.2.4 but setup.py  of torchcde is looking for version >= 0.2.5?

I could only pip install by changing:
install_requires = ['torch>=1.7.0', 'torchdiffeq>=0.2.0',
                    'torchsde @ git+https://github.com/google-research/torchsde.git>=0.2.5']
to ...
install_requires = ['torch>=1.7.0', 'torchdiffeq>=0.2.0', 'torchsde>=0.2.4']

**Comment by patrick-kidger** [comment]
Just fixed! Thanks.
(This happened because I'm a developer of torchsde as well, and we have a version 0.2.5 that isn't yet released... so it worked for me!)
