### ISSUE TITLE
Breaking install

### ISSUE THREAD

**Issue by howardjp** [patrick-kidger/torchcde#27]
'torchsde @ git+https://github.com/google-research/torchsde.git>=0.2.4']

This line is breaking installation for me, whether or not I have the latest torchsde available.

**Comment by patrick-kidger** [comment]
Ach. I swear this worked when I tried it! But you're right, it's breaking things.
I've removed the version requirement, which should solve things for now. Let me know if this works / if it doesn't.

**Comment by howardjp** [comment]
Trust me, I've been there.  Yes, the current version is installing.

**Comment by howardjp** [comment]
A little context since I just put it on GitHub.  I've got a Docker image with TorchCDE on it for use on the [OpenScienceGrid](https://opensciencegrid.org/).  As soon as it is converted to a Singularity image by the OSG people, I will soak up every spare GPU cycle in the hemisphere! 

https://github.com/k3jph/torch-diffeq

**Comment by patrick-kidger** [comment]
Closing this as we now have both `torchsde` and `torchcde` available on PyPI, so installation should work smoothly.
