### ISSUE TITLE
publish `torchcde` on PyPI

### ISSUE THREAD

**Issue by Zymrael** [patrick-kidger/torchcde#29]
Any plan to publish `torchcde` on PyPI? It's inconvenient to build packages that rely on `torchcde` as a dependency since it is not served on PyPI. There are workarounds with some versioning tools, like `poetry`, which I'm using for `torchdyn`. But it'd be lovely to have this out. 

Linked to [this](https://github.com/google-research/torchsde/issues/96), which is also a bottleneck.

**Comment by patrick-kidger** [comment]
Alright, this should be all sorted!
