### ISSUE TITLE
CDEs with Image Data

### ISSUE THREAD

**Issue by AshCher51** [patrick-kidger/torchcde#41]
Hey Patrick!
I want to utilize neural CDEs for the purpose of time series with images at different time points, as opposed to structured data. 

I have seen that on the torchdiffeq repo, they use a convolutional layer in their "ODEFunc" in order to use image data. I was wondering if a similar approach could be taken with neural CDEs. I'm just not sure how to prepare the data for doing such with the interpolation and cubic spline. I was wondering if you had any suggestions for how I could go about doing this.

In addition (unrelated to the main question), I was wondering whether interpolation with the hermite cubic spline could be performed during model training, as opposed to beforehand during data preprocessing.

I would greatly appreciate any help with these questions. 

Regards,
Aashish

**Comment by patrick-kidger** [comment]
In other words, run a neural CDE over a video.

In principle this is definitely possible. Just interpolate your data as normal; then just use a convolutional vector field as normal. (I don't think anyone has tried it in a serious way -- or if they have they haven't published their results -- so I don't know how effective this is. Try it and find out? Perhaps one might wish to use some kind of optical-flow-based interpolation?)

Of course you can use interpolation during model training; it's mathematically equivalent. For most applications it's slower though, as you're just repeatedly re-interpolating the same training data.
