### ISSUE TITLE
Comparison to alternative ODE models

### ISSUE THREAD

**Issue by denizetkar** [patrick-kidger/torchcde#42]
Hi Patrick,

I'm really interested in your work and while I was reading the neural CDE paper carefully I came across this subsection where you compare neural CDEs <img src="https://render.githubusercontent.com/render/math?math=g_{\theta,X}(z, s)"> to seemingly alternative neural ODEs <img src="https://render.githubusercontent.com/render/math?math=h_{\theta}(z, X_{s})">. There, the conclusion was that any such neural ODE can be rewritten as a neural CDE but not vice versa.

However, I cannot convince myself this to be the case. Let's take a really simple example where the control input is a scalar, the hidden state is also a scalar and <img src="https://render.githubusercontent.com/render/math?math=h_{\theta}(z, X_{s})=X_{s}"> such that the hidden state is simply the integral of the control path <img src="https://render.githubusercontent.com/render/math?math=z_{s}=\int_{s_{0}}^{s_{1}}X_{s}ds">. Also, assume for the sake of simplicity that <img src="https://render.githubusercontent.com/render/math?math=s_{0}=0, s_{1}=10, X_{s}=1">. Therefore, the control path is constant. In this case we would expect <img src="https://render.githubusercontent.com/render/math?math=z_{s_{1}}=10">. However, in the formulation of neural CDE dynamics <img src="https://render.githubusercontent.com/render/math?math=g_{\theta,X}(z,s)=f_{\theta}(z)\frac{dX}{ds}(s)">, if the control path doesn't change neither does the hidden state. So, how would we be able to rewrite this very simple "neural ODE" which is just an identity function as a neural CDE?

Cheers,
Deniz

**Comment by patrick-kidger** [comment]
Hey Deniz, thanks for your interest. The answer is that the control should include time as a channel. That is, assume we're given some data `x_i` observed at times `t_i` and let `x` be such that `x(t_i) = x_i`. Then you should drive the CDE by the path `(t, x(t))`, not just `x(t)`.

If you check the technical statement of the theoretical result it should be including time as a channel. And it is for similar reasons that the paper also emphasises that time should be included as a channel when training models in practice. (As this really does affect expressivity of the model.)

Your example is a good one, though! This is actually the canonical example for demonstrating why time should be included as a channel: it's Example 3.8 in [On Neural Differential Equations](https://arxiv.org/abs/2202.02435). And conversely there exist results on universal approximation, comparison-to-alternative-ODEs, etc. stating that you can approximate anything as long as you do include time as a channel.

**Comment by denizetkar** [comment]
I appreciate the prompt reply 😊 I think now I understand why we must include also the time into the control path. However, I'm still wondering what exactly would be the form of such a neural CDE to calculate the integral of its "input path" 🤔 Do you think it is something trivial or would it be some complicated set of functions, one for the input network, one for the hidden dynamics, and one for the output network (borrowing terminology from [this](https://arxiv.org/abs/2002.08071))?

**Comment by patrick-kidger** [comment]
Using a CDE to compute the integral of its input path is straightforward. This is Example 3.2 in [On Neural Differential Equations](https://arxiv.org/abs/2202.02435).

**Comment by denizetkar** [comment]
That example is the perfect answer, brilliant! Thank you.
