### ISSUE TITLE
About how to use CDE in Variational Autoencoders?

### ISSUE THREAD

**Issue by Saltsmart** [patrick-kidger/torchcde#43]
Hello, Mr Kidger! This work gives me a lot insight!

I've create a repo [Forecast](https://github.com/Saltsmart/Forecast_with_Neural_ODE) (also mentioned in #39 ). It's not too hard to use CDE in Seq2Seq models, but how to use it in Variational Autoencoders?

Here is a qoutation about modeling uncertainty from your [paper](https://arxiv.org/abs/2005.08926v2):
> As presented here, Neural CDEs do not give any measure of uncertainty about their predictions. Such extensions are likely to be possible, given the close links between CDEs and SDEs, and existing work on Neural SDEs.

ODE_RNN arms GRU Cell which can model `h_0` and `h_0_std`. The latter can be viewed as "uncertainty" and is crucial to VAE architecture. Are there related work for how to model uncertainty using CDE?

**Comment by patrick-kidger** [comment]
Have a read of Chapter 4 of [On Neural Differential Equations](https://arxiv.org/abs/2202.02435).
