### ISSUE TITLE
Integration to pytorch lighting pipeline

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [patrick-kidger/torchcde#44]
I'm trying to integrate torchcde to a BTC price prediction pipeline using pytorch lighting but I'm not able to figure out how to do it based on the examples provided. 
The goal is to predict if the price will go up or down in the next interval and by how much. So the target variable is **close**

## Scaled Data Example
<html><body>

minute | hour | day_of_week | vol | open | high | low | close_change | close
-- | -- | -- | -- | -- | -- | -- | -- | --
-1.000000 | -0.391304 | -0.666667 | -0.992874 | -0.635116 | -0.657622 | -0.621309 | 0.035182 | -0.654171
-0.818182 | -0.391304 | -0.666667 | -0.993615 | -0.647342 | -0.663678 | -0.625783 | 0.014025 | -0.658862
-0.636364 | -0.391304 | -0.666667 | -0.997344 | -0.652328 | -0.668183 | -0.625867 | 0.035498 | -0.658792

</body>
</html>

Feel free to have a look at the [complete pipeline](https://colab.research.google.com/drive/1-98ZsUMaLb0cslPeYxmx2Vn7hwrLeU16?usp=sharing) 
Any orientation to how to put things into place would be highly appreciated!

**Comment by patrick-kidger** [comment]
I'm afraid I'm not a user of PyTorch Lightning, so this isn't something I can help with. Good luck.
