### ISSUE TITLE
much slower when using torchsde as backend.

### ISSUE THREAD

**Issue by Fei-u** [patrick-kidger/torchcde#47]
hello, im trying to using neural cde with some noise. I found torchsde is one choice of backend. But after solving the 2-dim-limits problems,  it becomes much slower than just using torchdiffeq. May I using in a wrong way or  is this the problem of neural sde ?
or can i have a better way to combine noise ?
thanks.

**Comment by patrick-kidger** [comment]
This is probably expected to be honest. We do this by adding on a zero diffusion term, which is pretty wasteful.

In any case, `torchcde` is now in maintenance mode only. For any new projects I would encourage using [Diffrax](https://github.com/patrick-kidger/diffrax) instead, which is much larger, more featureful, and much faster.

**Comment by Fei-u** [comment]
thanks for your reply.
I just have a look at the issues of Diffrax and appreciate your hard-working ! 
I have another problem before I try to adopt torchsde as backend of CDE.  I use a seq2seq structure on multivarious time-series forecasting problems while neural sde runs after the neural cde overs. The result only improved a little on one traffic dataset. The seq2seq's behaviour seems to be equivalent to neural CDE with a conv2d. I'm so confused.
