### ISSUE TITLE
Please consider create conda distribution (maybe conda-forge?)

### ISSUE THREAD

**Issue by Saltsmart** [patrick-kidger/torchcde#49]
`torchcde` has become a solid base of [our package for Neural ODEs](https://github.com/Saltsmart/Forecast_with_Neural_ODE).
Thanks for your contribution to the community :love_letter: !
It's pretty nice to have a conda distribution for torchcde. Would you consider upload `torchcde` to conda or conda-forge (some reference [here](https://levelup.gitconnected.com/publishing-your-python-package-on-conda-and-conda-forge-309a405740cf))?

**Comment by patrick-kidger** [comment]
Probably not, I'm afraid. Conda already supports installing via PyPI and pip, so the overhead of maintaining a separate distribution channel isn't really worth it.

Besides which, I'd recommend using [Diffrax](https://github.com/patrick-kidger/diffrax) for any new projects. torchcde was just a small research project, whilst Diffrax is my propely supported library (that we use internally at Google).
