### ISSUE TITLE
Basic prediction problem.

### ISSUE THREAD

**Issue by andrewcztrack** [patrick-kidger/torchcde#9]
Hi @patrick-kidger !! I hope your well and staying safe during these times.

For a basic single variable prediction problem can this model be used.

for example for the below date -
```python
import numpy as np

import yfinance as yf
data = yf.download("SPY", start="2017-01-01", end="2017-04-30")['Adj Close']

y=data.to_numpy()
X=np.linspace(1, len(data))
```

**Comment by andrewcztrack** [comment]
Would this model be over the top or could it be used for prediction of future values.
Kind regards and thanks,
Andrew

**Comment by patrick-kidger** [comment]
In the sense of time series forecasting? Sure. You could do a sequence-to-sequence encoder/decoder pair. Neural CDE as the encoder, then probably a Neural ODE as the decoder.
